#!/bin/bash -x
plugins_list="ace-editor
amazon-ecr
antisamy-markup-formatter
apache-httpcomponents-client-4-api
authentication-tokens
aws-credentials
aws-java-sdk
blueocean-autofavorite
blueocean-bitbucket-pipeline
blueocean-commons
blueocean-config
blueocean-core-js
blueocean-dashboard
blueocean-display-url
blueocean-events
blueocean-git-pipeline
blueocean-github-pipeline
blueocean-i18n
blueocean-jwt
blueocean-personalization
blueocean-pipeline-api-impl
blueocean-pipeline-editor
blueocean-pipeline-scm-api
blueocean-rest
blueocean-rest-impl
blueocean-web
bouncycastle-api
branch-api
build-monitor-plugin
cloudbees-bitbucket-branch-source
cloudbees-folder
command-launcher
credentials
credentials-binding
discard-old-build
display-url-api
docker-build-publish
docker-commons
docker-workflow
durable-task
envinject
envinject-api
extended-read-permission
external-monitor-job
favorite
ghprb
git
git-client
git-server
github
github-api
github-branch-source
github-oauth
greenballs
handlebars
handy-uri-templates-2-api
htmlpublisher
jackson2-api
jacoco
jenkins-design-language
job-dsl
jquery-detached
jsch
junit
ldap
mailer
matrix-auth
matrix-project
mercurial
momentjs
pam-auth
pipeline-build-step
pipeline-graph-analysis
pipeline-input-step
pipeline-milestone-step
pipeline-model-api
pipeline-model-declarative-agent
pipeline-model-definition
pipeline-model-extensions
pipeline-rest-api
pipeline-stage-step
pipeline-stage-tags-metadata
pipeline-stage-view
pipeline-utility-steps
plain-credentials
pubsub-light
rebuild
resource-disposer
sbt
scm-api
script-security
sonar
sse-gateway
ssh-credentials
structs
summary_report
swarm
timestamper
token-macro
variant
windows-slaves
workflow-aggregator
workflow-api
workflow-basic-steps
workflow-cps
workflow-cps-global-lib
workflow-durable-task-step
workflow-job
workflow-multibranch
workflow-scm-step
workflow-step-api
workflow-support
ws-cleanup
zap"

IFS=$'\n'
for plugin in ${plugins_list}
do
	sudo java -jar jenkins-cli.jar -s http://127.0.0.1:8080/ -auth admin:admin install-plugin ${plugin}
done

sudo service jenkins start
